export const USER_SIGNUP = 'USER_SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_STARTED = 'SIGNUP_STARTED'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const UPDATE_NAME_SUCCESS = 'UPDATE_NAME_SUCCESS '
export const UPDATE_NAME_STARTED = 'UPDATE_NAME_STARTED'
export const UPDATE_NAME_FAILURE = 'UPDATE_NAME_FAILURE'

export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS'
export const UPDATE_EMAIL_STARTED = 'UPDATE_EMAIL_STARTED'
export const UPDATE_EMAIL_FAILURE = 'UPDATE_EMAIL_FAILURE'


