export const USER_SIGNUP = 'USER_SIGNUP'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_STARTED = 'SIGNUP_STARTED'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'

export const UPDATE_NAME_SUCCESS = 'UPDATE_NAME_SUCCESS '
export const UPDATE_NAME_STARTED = 'UPDATE_NAME_STARTED'
export const UPDATE_NAME_FAILURE = 'UPDATE_NAME_FAILURE'

export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS'
export const UPDATE_EMAIL_STARTED = 'UPDATE_EMAIL_STARTED'
export const UPDATE_EMAIL_FAILURE = 'UPDATE_EMAIL_FAILURE'


export const QUERY_SUCCESS = 'QUERY_SUCCESS'
export const QUERY_STARTED = 'QUERY_STARTED'
export const QUERY_FAILURE = 'QUERY_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_STARTED = 'LOGOUT_STARTED'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'


